name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test
        setup-command: conda install python=3.8 --yes; conda install -c potassco clingo
          --yes
        command: "/usr/share/miniconda/bin/python3.8 asp/test.py -e asp/sudoku.lp
          -i asp/instances -s asp/solutions -t 100 -c /usr/share/miniconda/bin/clingo"
        input: ''
        expected-output: SUCCESS
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
